-   id: check-email-domain
    name: check commiter's email
    description: ensure that the domain of the commiter's email is correct.
    entry: check-email-domain
    args: ["dronetag.cz", "dronetag.com"]
    language: python
