name: main

on:
  push:
    branches: [main]
    tags: '*'
  pull_request:

jobs:
  main-windows:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.5.0
    with:
      env: '["py37", "py311"]'
      os: windows-latest
  main-linux:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.5.0
    with:
      env: '["py37", "py38", "py311"]'
      os: ubuntu-latest
